name: restaurant_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  flutter_native_splash: ^2.1.2+1
  http: ^0.13.4
  provider: ^5.0.0
  path_provider: ^2.0.9
  equatable: ^2.0.3
  sqflite: ^2.0.2+1
  shared_preferences: ^2.0.13
  android_alarm_manager_plus: ^2.0.5
  intl: ^0.17.0
  flutter_local_notifications: ^9.4.1
  rxdart: ^0.27.3
  salomon_bottom_bar: ^3.3.0

flutter_native_splash:
  android: true
  ios: true
  color: "#F4F4F4"
  image: assets/restaurants_splash.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
